### ISSUE TITLE
DAX UDFs

### ISSUE THREAD

**Issue by EvaluationContext** [microsoft/vscode-tmdl#19]
Get alot of `Unexpected Tuple` errors when defining DAX User Defined Functions (UDFs) parameters, and `=>` unexpected.

<img width="849" height="730" alt="Image" src="https://github.com/user-attachments/assets/25e462f7-def9-4c33-b689-f66412af9636" />

Example code here:

https://github.com/EvaluationContext/daxlib/blob/daxlib.svg/v0.1.2-beta/packages/d/daxlib.svg/0.1.2-beta/lib/functions.tmdl

**Comment by muhssamy** [comment]
i have the same issue also

**Comment by ggongg** [comment]
Thanks for providing your feedback! The dev team is investigating the issue and we will send more updates once we have them.

**Comment by ggongg** [comment]
Hi @EvaluationContext thanks again for creating this issue. The team has investigated and pushed a fix which will be part of the next release (expected around next week) so we would recommend checking with the newest version of the app once the new release comes out.

**Comment by RuiRomano** [comment]
Seems related, but also reports issues when using UDF functions in DAX measures:

<img width="1468" height="746" alt="Image" src="https://github.com/user-attachments/assets/d2391e46-1686-42ab-8ed0-940faa81fedb" />

**Comment by ggongg** [comment]
Hi @EvaluationContext @RuiRomano the updated release is now available, please let us know if you are still facing the same issue after updating. Thanks!

**Comment by EvaluationContext** [comment]
Looked today and is better but still get ... is not a function:
   - `ISNUMERIC()`
   - `ISDATETIME()`
   - any UDF called in another UDF

**Comment by otykier** [comment]
Just tried 1.6.0, and it still shows an error when calling an UDF:

<img width="1139" height="276" alt="Image" src="https://github.com/user-attachments/assets/0dc7f1bb-67c6-4dae-8a12-700e902be936" />

My `functions.tmdl` file looks like this:

<img width="1039" height="230" alt="Image" src="https://github.com/user-attachments/assets/c77f2212-be26-4c09-a40c-e8a9cfda28e5" />

**Comment by ggongg** [comment]
Hi @EvaluationContext, @otykier 
Thank you for confirming the update and sharing the details. We’re glad to hear things are better, but we understand the remaining issue with UDF calls (e.g., ISNUMERIC(), ISDATETIME(), and nested UDF scenarios).
I will share this with the team. It appears related to how the extension parses user-defined functions within other functions, which is a known limitation. In the meantime, could you share:

The exact error message from the problems pane or screenshot you’re seeing (if not already included).

This will help us validate the fix against your scenario. We’ll keep you updated as soon as a patch or workaround is available.
Thanks for your patience and for helping us improve the extension!

**Comment by ArturNawrocki** [comment]
Any news reagarding that? It has been couple of months... If you have trouble with this please open-source it

**Comment by minghan** [comment]
Thanks! This gap with the introspection functions (ISNUMERIC(), ISDATETIME(), etc) should have been addressed with version 1.6.5.

The remaining issue with usage of UDFs within a functions.tmdl is a known one.

**Comment by EvaluationContext** [comment]
Nested UDF issue still remains

<img width="1646" height="1307" alt="Image" src="https://github.com/user-attachments/assets/4e64a62a-39d0-4204-8c0d-249c43ac7845" />
